platform :ios, ‘8.0’
use_frameworks!
target ‘TongParty’ do
pod 'AFNetworking'
pod 'Masonry'
pod 'SDWebImage'
pod 'ReactiveCocoa','2.5'
pod 'MJExtension'
pod 'MJRefresh'
pod 'UMengUShare/UI’
pod 'UMengUShare/Social/Sina'
pod 'UMengUShare/Social/WeChat'
pod 'UMengUShare/Social/QQ'
pod 'YYText'
pod 'YYWebImage'
pod 'pop'
pod 'MBProgressHUD'
pod 'DZNEmptyDataSet'   #空列表提示
pod 'AMap3DMap' #3D地图SDK
pod 'AMapSearch' #搜索功能
pod 'AMapLocation' #搜索功能
end
